[project]
name = "data-engineering-home-assignment"
version = "0.1.0"
description = ""
authors = [{name = "oamar"}]
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pyspark (==3.5.5)",
    "boto3"
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["assignment*"]
