AWSTemplateFormatVersion: '2010-09-09'
Description: 'Stocks Processing Pipeline'

Parameters:
  S3BucketName:
    Type: String
    Default: data-engineer-assignment-oamar
    Description: Name of the S3 bucket for data storage

  GlueJobName:
    Type: String
    Default: stocks-stats-job
    Description: Name of the Glue job

  GlueRoleName:
    Type: String
    Default: glue-service-role
    Description: Name of the Glue service role

  DatabaseName:
    Type: String
    Default: stocks_stats_db
    Description: Name of the Glue catalog database

Resources:
  # S3 Bucket for storing data and results
  DataEngineeringBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${S3BucketName}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # Glue Service Role
  GlueServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${GlueRoleName}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: glue.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DataEngineeringBucket}/*'
                  - !Sub 'arn:aws:s3:::${DataEngineeringBucket}'

  # Glue Catalog Database
  GlueDatabase:
    Type: AWS::Glue::Database
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Sub '${DatabaseName}'
        Description: 'Database for stocks data processing pipeline'

  # Glue Job
  GlueJob:
    Type: AWS::Glue::Job
    Properties:
      Name: !Sub '${GlueJobName}'
      Role: !Ref GlueServiceRole
      Command:
        Name: glueetl
        ScriptLocation: !Sub 's3://${DataEngineeringBucket}/scripts/glue.py'
        PythonVersion: 3
      DefaultArguments:
        '--job-language': python
        '--enable-metrics': true
        '--enable-continuous-cloudwatch-log': true
        '--extra-py-files': !Sub 's3://${DataEngineeringBucket}/libs/assignment.zip'
        '--JOB_NAME': !Sub '${GlueJobName}'
        '--S3_BUCKET': !Ref DataEngineeringBucket
        '--DATA_PATH': !Sub 's3://${DataEngineeringBucket}/input/stocks_data.csv'
        '--ENVIRONMENT': 'GLUE'
      MaxCapacity: 10
      GlueVersion: 4.0
      Timeout: 60

  # Glue Crawler
  Crawler:
    Type: AWS::Glue::Crawler
    Properties:
      Name: !Sub '${GlueJobName}-crawler'
      Role: !Ref GlueServiceRole
      DatabaseName: !Ref GlueDatabase
      Targets:
        S3Targets:
          - Path: !Sub 's3://${S3BucketName}/results/'
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: LOG

  # Glue Catalog Tables for Results
  AverageDailyReturnTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: average_daily_return
        Description: 'Average daily return of all stocks per date'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Columns:
            - Name: date
              Type: date
            - Name: average_return
              Type: double
          Location: !Sub 's3://${DataEngineeringBucket}/results/objective_1_average_daily_return/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: true
#        PartitionKeys:
#          - Name: date
#            Type: date

  HighestWorthTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: highest_worth
        Description: 'Stock with highest average worth'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: value
              Type: double
          Location: !Sub 's3://${DataEngineeringBucket}/results/objective_2_highest_trade_worth/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: true

  MostVolatileTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: most_volatile
        Description: 'Most volatile stock by annualized standard deviation'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: standard_deviation
              Type: double
          Location: !Sub 's3://${DataEngineeringBucket}/results/objective_3_most_volatile_stock/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: true

  Top30DayReturnsTable:
    Type: AWS::Glue::Table
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref GlueDatabase
      TableInput:
        Name: top_30day_returns
        Description: 'Top 3 stocks with highest 30-day returns'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        StorageDescriptor:
          Columns:
            - Name: ticker
              Type: string
            - Name: date
              Type: date
          Location: !Sub 's3://${DataEngineeringBucket}/results/objective_4_top_30d_returns/'
          InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
          OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
          SerdeInfo:
            SerializationLibrary: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
          Compressed: true
#        PartitionKeys:
#          - Name: ticker
#            Type: string

Outputs:
  S3BucketName:
    Description: 'Name of the S3 bucket'
    Value: !Ref DataEngineeringBucket
    Export:
      Name: !Sub '${AWS::StackName}-S3Bucket'

  GlueJobName:
    Description: 'Name of the Glue job'
    Value: !Ref GlueJob
    Export:
      Name: !Sub '${AWS::StackName}-GlueJob'

  GlueDatabaseName:
    Description: 'Name of the Glue catalog database'
    Value: !Ref GlueDatabase
    Export:
      Name: !Sub '${AWS::StackName}-GlueDatabase'
